### PR TITLE
Add default command name to DI config

### LINKED ISSUE #126: Missing default command name in DI tags
As I just installed Symfony 3.4, I get the following error:

```
Call to undefined method Doctrine\Bundle\DoctrineCacheBundle\Command\ContainsCommand::getDefaultName()
```

I believe this can be solved by updating the tags for the service definitions of the commands in `Resources/services.xml`

```xml
<services>
        <service id="doctrine_cache.contains_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\ContainsCommand">
            <tag name="console.command" />
        </service>
        <service id="doctrine_cache.delete_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\DeleteCommand">
            <tag name="console.command" />
        </service>
        <service id="doctrine_cache.flush_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\FlushCommand">
            <tag name="console.command" />
        </service>
        <service id="doctrine_cache.stats_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\StatsCommand">
            <tag name="console.command" />
        </service>
</services>
```
Would become:

```xml
<services>
        <service id="doctrine_cache.contains_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\ContainsCommand">
            <tag name="console.command" command="doctrine:cache:contains" />
        </service>
        <service id="doctrine_cache.delete_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\DeleteCommand">
            <tag name="console.command" command="doctrine:cache:delete" />
        </service>
        <service id="doctrine_cache.flush_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\FlushCommand">
            <tag name="console.command" command="doctrine:cache:flush" />
        </service>
        <service id="doctrine_cache.stats_command" class="Doctrine\Bundle\DoctrineCacheBundle\Command\StatsCommand">
            <tag name="console.command" command="doctrine:cache:stats" />
        </service>
</services>
```

### PR DESCRIPTION
**Pull request by johmanx10**
Closes #126 

This solves compilation errors in Symfony >= 3.4

@fabpot Consequently I have issues with this default command name in all my bundles that register commands using tags. Is there something I'm doing incorrectly here?

### CODE REVIEW

**Comment by alcaeus** [comment]
Something is fishy. Yes, this fixes the error, but if you ask me this is a BC break introduced in https://github.com/symfony/symfony/pull/23887. @fabpot @nicolas-grekas what do you think?

**Comment by johmanx10** [comment]
This pull request will be closed because the corresponding issue is deemed invalid.
